### ISSUE TITLE
support for topologySpreadConstraints in k8s deployment

### ISSUE THREAD

**Issue by haroldorquesta** [sai3010/Typesense-Kubernetes-Operator#25]
Any plans on supporting this feature? in our use case we need the replicas to be spread on different nodes and currently we are not able to pass this to the statefulset deployment with the `TypesenseOperator` deployment kind.

Sample config

```yaml
apiVersion: typesenseproject.org/v1
kind: TypesenseOperator
metadata:
  name: type-operator
spec:
  replicas: 3
  namespace: typesense
  image: typesense/typesense:27.1
  env:
  - name: APIKEY
    valueFrom:
      secretKeyRef:
        name: typesense-apikey
        key: apikey
  resources:
    requests:
      memory: 100Mi
      cpu: "100m"
    limits:
      memory: 200Mi
      cpu: "100m"
  nodeSelector:
    kubernetes.io/os: linux
  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app: typesense
      maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
config:
  secret: "typesense-apikey"
  env:
    TYPESENSE_ENABLE_CORS: "true"
```
