### ISSUE TITLE
API calls fails due to api key not being set

### ISSUE THREAD

**Issue by drawm** [sai3010/Typesense-Kubernetes-Operator#26]
**Describe the bug**
When following the installation guide, every node will decline all request due to "invalid key" not being provided.
This is due to the `typesense-operator-sa` not having permission to read the api key form the secrets 

**To Reproduce**
Make a minimal installation
* While following the [installation guide](https://sai3010.github.io/Typesense-Kubernetes-Operator/deployment/)
* Specify `default` as the namespace when creating resource in `./deploy` (will not accept any other namespace because `default` is hardcoded in `rbac.yaml`)
* Change the namespace in `operator-config.yaml` to `default` to match the namespace used in `rbac.yaml` 
* Follow remaining steps in the installation guide
* Port forward a typesense node to call its api `kubectl --namespace default port-forward typesense-0 8108:8108`
* In another terminal curl the api using the secret key you created (`MWYyZDFlMmU2N2Rm` in the installation guide)
`curl -H "x-typesense-api-key: MWYyZDFlMmU2N2Rm" "http://localhost:8108/collections"` 

The expected response should be `[]` but the request will be declined due to the api key being "invalid"

If you look at the operator's logs, you'll see it failing to retrieve the api key. `secrets "typesense-apikey" is forbidden: User "system:serviceaccount:default:typesense-operator-sa" cannot get resource "secrets" in API group "" in the namespace "default"`

**Expected behavior**
* Requests should return the appropriate payload when making a call with the right key
* Typesense operator should be able to access its secrets

**Please complete the following information:**
 - Kubernetes version - 1.30.5 (using rancher-desktop)
 - Typesense version - 27.1
 - Cloud provider or self-managed? - self-managed

## Additional context
**Guide & Namespace issues**
The guide wrongly suggest the user specify a namespace with every `kubectl create` while some resources have hardcoded namespaces and will fail to be created if any namespace other than "default" is specified

`operator-config.yaml` has the namespace `typesense` hardcoded which will prevent it from working due to `default` being the namespace used in other part of the codebase. 

Ideally no namespace should be hardcoded unless necessary, or at least the guide shouldn't lead the user into messing the installation by specifying the wrong namespace.

**Potential Fix**
Fixed locally by adding the following ClusterRole and ClusterRoleBinding, I'm not 100% sure its production ready but its a start
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
  - apiGroups: [""]
    #
    # at the HTTP level, the name of the resource for accessing Secret
    # objects is "secrets"
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
# Grant permission to read api key secret
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: default
subjects:
  - kind: ServiceAccount
    name: typesense-operator-sa
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
```
